jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.10
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'
    - name: Create and activate virtual environment
      run: |
        python3.10 -m venv chroma_env
        source chroma_env/bin/activate
